//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vitinerario.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Privacy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Privacy() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vitinerario.Resources.Views.Shared.Privacy", typeof(Privacy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We reserve the right to update or modify this Privacy Policy from time to time in order to reflect legal, technical, or organizational changes, as well as the evolution of the services provided..
        /// </summary>
        public static string Changes_P1 {
            get {
                return ResourceManager.GetString("Changes_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The most current version will always be published on this page together with the latest update date. Where material changes occur, we may adopt additional notice measures where required by applicable law..
        /// </summary>
        public static string Changes_P2 {
            get {
                return ResourceManager.GetString("Changes_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changes to this Privacy Policy and contact.
        /// </summary>
        public static string Changes_Title {
            get {
                return ResourceManager.GetString("Changes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a For information about the processing of personal data or to exercise your rights, you can contact us at.
        /// </summary>
        public static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questions about privacy?.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Technical device information such as model, operating system, language, app version, and general device parameters..
        /// </summary>
        public static string Data_Item1 {
            get {
                return ResourceManager.GetString("Data_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IP address, online identifiers, and device identifiers, including advertising IDs where used for advertising or analytics purposes..
        /// </summary>
        public static string Data_Item2 {
            get {
                return ResourceManager.GetString("Data_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Usage and interaction data, such as screens viewed, time spent in the app, in-app events, and interactions with content or features..
        /// </summary>
        public static string Data_Item3 {
            get {
                return ResourceManager.GetString("Data_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diagnostic data, crash logs, performance information, and data related to the proper functioning of the application..
        /// </summary>
        public static string Data_Item4 {
            get {
                return ResourceManager.GetString("Data_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Any information voluntarily provided by the user through contact requests or communications sent to the developer..
        /// </summary>
        public static string Data_Item5 {
            get {
                return ResourceManager.GetString("Data_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a While using the app, we may collect, directly or through third-party providers integrated into the application, certain categories of personal and technical data..
        /// </summary>
        public static string Data_P1 {
            get {
                return ResourceManager.GetString("Data_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The data actually processed may vary depending on the app configuration, device settings, the user’s Google account settings, consent choices, and enabled services..
        /// </summary>
        public static string Data_P2 {
            get {
                return ResourceManager.GetString("Data_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data collected.
        /// </summary>
        public static string Data_Title {
            get {
                return ResourceManager.GetString("Data_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Directory.
        /// </summary>
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This Privacy Policy explains how Vitinerario collects, uses, shares, and protects the personal data of users who access the mobile app and related services..
        /// </summary>
        public static string Intro_P1 {
            get {
                return ResourceManager.GetString("Intro_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use of the app may involve the processing of certain technical and usage information necessary to operate the service, improve the user experience, measure performance, and, where applicable, display advertising..
        /// </summary>
        public static string Intro_P2 {
            get {
                return ResourceManager.GetString("Intro_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a By using Vitinerario, the user acknowledges this notice. Where required by applicable law, processing subject to consent will only take place after such consent has been validly provided..
        /// </summary>
        public static string Intro_P3 {
            get {
                return ResourceManager.GetString("Intro_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Introduction.
        /// </summary>
        public static string Intro_Title {
            get {
                return ResourceManager.GetString("Intro_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a March 11, 2026.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Changes and contact.
        /// </summary>
        public static string Nav_ChangesContact {
            get {
                return ResourceManager.GetString("Nav_ChangesContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data collected.
        /// </summary>
        public static string Nav_DataCollected {
            get {
                return ResourceManager.GetString("Nav_DataCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Introduction.
        /// </summary>
        public static string Nav_Intro {
            get {
                return ResourceManager.GetString("Nav_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rights and security.
        /// </summary>
        public static string Nav_RightsSecurity {
            get {
                return ResourceManager.GetString("Nav_RightsSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Third-party services.
        /// </summary>
        public static string Nav_ThirdParties {
            get {
                return ResourceManager.GetString("Nav_ThirdParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use of data.
        /// </summary>
        public static string Nav_UseOfData {
            get {
                return ResourceManager.GetString("Nav_UseOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Privacy Policy.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Where applicable, users may request information about processed data, as well as access, rectification, erasure, or restriction of processing..
        /// </summary>
        public static string Rights_Item1 {
            get {
                return ResourceManager.GetString("Rights_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Users may object to processing based on legitimate interest, where provided by law..
        /// </summary>
        public static string Rights_Item2 {
            get {
                return ResourceManager.GetString("Rights_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Users may manage certain preferences directly through their device, their Google account, or any consent tools displayed in the app..
        /// </summary>
        public static string Rights_Item3 {
            get {
                return ResourceManager.GetString("Rights_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Where required by applicable law, users may withdraw previously given consent at any time, without affecting the lawfulness of processing carried out before withdrawal..
        /// </summary>
        public static string Rights_Item4 {
            get {
                return ResourceManager.GetString("Rights_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a We adopt reasonable technical and organizational measures to protect data against unauthorized access, loss, disclosure, alteration, or destruction. However, no method of transmission or electronic storage can be considered completely secure..
        /// </summary>
        public static string Rights_P1 {
            get {
                return ResourceManager.GetString("Rights_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Where data is processed by third-party providers such as Google, Firebase, or AdMob, part of the information may be retained and processed according to their own policies and retention periods..
        /// </summary>
        public static string Rights_P2 {
            get {
                return ResourceManager.GetString("Rights_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rights and security.
        /// </summary>
        public static string Rights_Title {
            get {
                return ResourceManager.GetString("Rights_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last updated:.
        /// </summary>
        public static string Sidebar_LastUpdatedLabel {
            get {
                return ResourceManager.GetString("Sidebar_LastUpdatedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Services currently used.
        /// </summary>
        public static string ThirdParty_Box_Title {
            get {
                return ResourceManager.GetString("ThirdParty_Box_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Firebase: infrastructure, technical analytics, possible crash reporting, and related services..
        /// </summary>
        public static string ThirdParty_Item1 {
            get {
                return ResourceManager.GetString("ThirdParty_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google Analytics for Firebase: collection of events and aggregated statistics regarding app usage..
        /// </summary>
        public static string ThirdParty_Item2 {
            get {
                return ResourceManager.GetString("ThirdParty_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Google AdMob: display and measurement of ads, including possible management of personalized or non-personalized advertising..
        /// </summary>
        public static string ThirdParty_Item3 {
            get {
                return ResourceManager.GetString("ThirdParty_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The application integrates third-party services that may process data on their own behalf or on behalf of the controller, in accordance with their respective terms and privacy notices..
        /// </summary>
        public static string ThirdParty_P1 {
            get {
                return ResourceManager.GetString("ThirdParty_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a These providers may process data such as IP address, device identifiers, diagnostic information, usage statistics, interactions with content, and information required to provide their services..
        /// </summary>
        public static string ThirdParty_P2 {
            get {
                return ResourceManager.GetString("ThirdParty_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a For more details about processing carried out by these providers, users should also consult the privacy notices published by the respective providers..
        /// </summary>
        public static string ThirdParty_P3 {
            get {
                return ResourceManager.GetString("ThirdParty_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Third-party services.
        /// </summary>
        public static string ThirdParty_Title {
            get {
                return ResourceManager.GetString("ThirdParty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data is processed solely for purposes related to providing the service, security, analytics, app improvement, and, where applicable, advertising management..
        /// </summary>
        public static string Usage_Box_Text {
            get {
                return ResourceManager.GetString("Usage_Box_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Why we process this data.
        /// </summary>
        public static string Usage_Box_Title {
            get {
                return ResourceManager.GetString("Usage_Box_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In particular, data may be used to provide app features, monitor stability and performance, analyze service usage, prevent abuse or malfunction, and improve the overall quality of the user experience..
        /// </summary>
        public static string Usage_P1 {
            get {
                return ResourceManager.GetString("Usage_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a If AdMob ads are displayed, some data may also be processed for ad delivery, measurement, and optimization, in accordance with the user’s choices and applicable law..
        /// </summary>
        public static string Usage_P2 {
            get {
                return ResourceManager.GetString("Usage_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Use of data.
        /// </summary>
        public static string Usage_Title {
            get {
                return ResourceManager.GetString("Usage_Title", resourceCulture);
            }
        }
    }
}
